name: CD
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: ./.github/actions/ci
      - uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "sdist"
          ignore_dev_requirements: "yes"
